### ISSUE TITLE
Organizationの名前

### ISSUE THREAD

**Issue by kou029w** [tinkering-mbit/digitalDice#1]
本リポジトリとは直接関係ないIssueですが他にどこに記載してよいか判断つかなかったのでこちらに起票します。ご了承下さい。
Organization _tinkering-mbit_ なのですが、この名前に含まれる "mbit" は一般的に "megabit" の略記であることが多いように感じます。
これは意図通りでしょうか。

**Comment by kou029w** [comment]
micro:bit を意図しているのであればそのまま "tinkering-microbit" とするのが望ましいように感じましたが、やはり商標などの観点で法的リスクがあるという感じなのですかね

というより [Community Guidelines](https://microbit.org/community/) では "micro:bit" を含めるのは非推奨なのですねw

> Our preference is that you do not use ‘micro:bit’ at all in your organisation name.

**Comment by satakagi** [comment]
tinkering:bitにしようかという話を @chibitaki さんとしていたのですが、もうすでにあったので、mbitにしてみた感じです。　それ以上の意味はないので何かより良い名称があれば～

**Comment by kou029w** [comment]
回答ありがとうございます
micro:bitの略記というと[micro:bit runtime](https://lancaster-university.github.io/microbit-docs/)で使われている "uBit" を先に連想しましたが、なるほど、"micro:bit"でも"megabit"でもなく、もともと"tinkering:bit"としたかったが名前が被るのを避けるために加えている "m" なのですね
特にそれ以上の意味は無いということで本件解決としますw
